// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WADFC.Models;

namespace WADFC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WADFC.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Completed")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventImage")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("WADFC.Models.Fight", b =>
                {
                    b.Property<int>("FightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("EventID")
                        .HasColumnType("int");

                    b.Property<int?>("FighterAID")
                        .HasColumnType("int");

                    b.Property<int?>("FighterBID")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<string>("Winner")
                        .HasColumnType("varchar(100)");

                    b.HasKey("FightID");

                    b.HasIndex("EventID");

                    b.HasIndex("FighterAID");

                    b.HasIndex("FighterBID");

                    b.ToTable("Fights");
                });

            modelBuilder.Entity("WADFC.Models.Fighter", b =>
                {
                    b.Property<int>("FighterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("Draw")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Loss")
                        .HasColumnType("int");

                    b.Property<int>("NoContest")
                        .HasColumnType("int");

                    b.Property<int>("Reach")
                        .HasColumnType("int");

                    b.Property<string>("Stance")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<int>("Win")
                        .HasColumnType("int");

                    b.HasKey("FighterID");

                    b.ToTable("Fighters");
                });

            modelBuilder.Entity("WADFC.Models.Fight", b =>
                {
                    b.HasOne("WADFC.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID");

                    b.HasOne("WADFC.Models.Fighter", "FighterA")
                        .WithMany()
                        .HasForeignKey("FighterAID");

                    b.HasOne("WADFC.Models.Fighter", "FighterB")
                        .WithMany()
                        .HasForeignKey("FighterBID");

                    b.Navigation("Event");

                    b.Navigation("FighterA");

                    b.Navigation("FighterB");
                });
#pragma warning restore 612, 618
        }
    }
}
